namespace: field-guides-prod
app_name: site-v2

openshift_cluster_content:
- object: projects
  content:
  - name: "create {{ namespace }} environment"
    template: "{{ inventory_dir }}/../.openshift/projects/projects.yml"
    action: create
    params_from_vars:
      NAMESPACE: "{{ namespace }}"
    namespace: "{{ namespace }}"
  - name: "create promoter account"
    template: "{{ inventory_dir }}/../.openshift/templates/promoter-sa.yml"
    params_from_vars:
      NAMESPACE: "{{ namespace }}"
      JENKINS_NAMESPACE: "{{ namespace }}"
    namespace: "{{ namespace }}"
- object: deployments
  content:
  - name: "deploy to {{ namespace }} environment"
    template: "{{ inventory_dir }}/../.openshift/templates/deployment.yml"
    namespace: "{{ namespace }}"
    params_from_vars:
      APP_NAME: "{{ app_name }}"
