apiVersion: v1
kind: Template
metadata:
  name: pipeline-template
  labels:
    template-type: build
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      build: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ${OUTPUT_IMAGE_TYPE}
        name: ${OUTPUT_IMAGE}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nginx:latest
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
  status:
    lastVersion: 0
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: ${APP_NAME}-pipeline
  spec:
    source:
      git:
        uri: ${APPLICATION_SOURCE_REPO}
        ref: ${APPLICATION_SOURCE_REF}
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
        env:
          - name: APPLICATION_SOURCE_REPO
            value: ${APPLICATION_SOURCE_REPO}
          - name: APPLICATION_SOURCE_REF
            value: ${APPLICATION_SOURCE_REF}
    triggers:
      - type: ConfigChange
      - type: GitHub
        github:
          secret: d8g73hc87
parameters:
- name: APP_NAME
- name: OUTPUT_IMAGE
- name: OUTPUT_IMAGE_TYPE
- name: PUSH_SECRET
- name: APPLICATION_SOURCE_REPO
  value: https://github.com/redhat-cop/uncontained.io
- name: APPLICATION_SOURCE_REF
  value: master
