apiVersion: v1
kind: Template
labels:
  template: cluster-credentials-secret
metadata:
  annotations:
    description: Cluster Credential Secret
    tags: secret
    version: 1.0.0
  name: cluster-credentials-secret
objects:
- apiVersion: v1
  stringData:
    api: ${API_URL}
    registry: ${REGISTRY_URL}
    token: "${TOKEN}"
  data:
  kind: Secret
  metadata:
    name: ${SECRET_NAME}
  type: Opaque
parameters:
- description: The name for the application.
  name: SECRET_NAME
  required: true
  value: prod-credentials
- description: The API URL
  name: API_URL
  required: true
- description: The Registry Route URL
  name: REGISTRY_URL
  required: true
- description: Service Account Token
  name: TOKEN
  required: true
