apiVersion: v1
kind: Template
metadata:
  name: route-template
  labels:
    template-type: deployment
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    host: ${HOSTNAME}
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${APP_NAME}
      weight: 100
    wildcardPolicy: None
parameters:
- name: APP_NAME
  required: true
- name: HOSTNAME
  required: true
