---
title: Brand Elements
linkTitle: Brand Elements
---

= Branding and Styling for Uncontained

This page serves as a design and styling guide for the site.

== Admonitions

NOTE: This is a _Note_ block

TIP: This is a _Tip_ block with an `inline code block` in it.

WARNING: This warns readers of something not to do

IMPORTANT: This notifies of very critical information

== Code Styling

Here is a code block with no specific syntax highlighting:

----
...
[OSEv3:vars]
ansible_user=root

deployment_type=openshift-enterprise
openshift_release=v3.7

openshift_master_api_port=443
openshift_master_console_port=443
openshift_portal_net=172.30.0.0/16
osm_cluster_network_cidr=10.128.0.0/14

openshift_master_cluster_hostname=console-int.c1-ocp.myorg.com <1>
openshift_master_cluster_public_hostname=console.c1-ocp.myorg.com <2>

openshift_master_default_subdomain=apps.c1-ocp.myorg.com <3>
...
----

Here is a `code block` containing `ini` syntax:

[source,ini]
----
# hosts file for c1-ocp.myorg.com
[OSEv3:children]
masters
etcd
nodes

[OSEv3:vars]

[masters]
[etcd]
[nodes]
----

Here is a code block containing `yaml`:

[source,yaml]
----
apiVersion: v1
kind: BuildConfig
metadata:
  name: sample-pipeline
  labels:
    name: sample-pipeline
spec:
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node("maven") {
          stage("echo") {
            println("Hello World")
          }
        }
----

== Table Styling

.Table Title
[width="100%",cols="3,6,10",options="header"]
|=========================================================
|Column1 Heading |Another Header |And one more

|Row 1 value |A description of the row | `$ a related code snippet`

|Ro1 2 value|The description of row 2. This one is a littler longer and gives us an opportunity to see how text might wrap.
| `# This is a code block for row 2`
|Some other stuff |This is the last row, let's see if anything's different | _Some formatted text_

|=========================================================
