name = "uncontained.io Theme"
license = "MIT"
licenselink = "https://github.com/redhat-cop/uncontained.io/blob/master/themes/uncontained.io/LICENSE.md"
description = "Hugo Theme for uncontained.io. Based on Blank theme by Vimux."
homepage = "http://uncontained.io/"
features = ["blog"]
min_version = 0.19

[author]
  name = "Red Hat Communities of Practice"
  homepage = "https://redhat-cop.github.io"
